### ISSUE TITLE
Dictionary 2021d

### ISSUE THREAD

**Issue by khangthk** [AlizaMedicalImaging/MDCM#1]
Please update dictionary to 2021d or is there any tool/tutorial to guide manual update of this.

**Comment by issakomi** [comment]
I have updated attributes and UIDs, also some other related changes like new CLOSEDPLANAR_XOR contour type for RTSTRUCT. There is also new Transfer Syntax: _Encapsulated Uncompressed Explicit VR Little Endian_, to support uncompressed image > 4GB. It is WIP, it is big change and there are probably no files with it. I shall add support for it little later, it is WIP.
